import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(process.env.SUNNY_NODE_PACKAGES+'/package.json');
const {chromium}=require('playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({viewport:{width:834,height:1194},hasTouch:true});
const page=await context.newPage(); const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
const start=async(query='')=>{await page.goto('http://127.0.0.1:4177/ui-preview/index.html?theme=light&'+query);await page.locator('#preview-writes').waitFor();};
const route=async(path)=>{await page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'));},path);await page.waitForTimeout(250);};
try {
  await start('editor');
  assert.equal(await page.getByRole('textbox',{name:'Importo',exact:true}).getAttribute('readonly'),'');
  assert.equal(await page.getByRole('button',{name:'1',exact:true}).isVisible(),true,'iPad touch keeps keypad at desktop width');
  await page.getByRole('button',{name:'1',exact:true}).click();
  await page.getByRole('button',{name:'+1',exact:true}).click();
  assert.equal(await page.locator('#preview-writes').textContent(),'1');
  assert.equal(await page.getByRole('dialog').count(),1);
  assert.equal(await page.getByRole('textbox',{name:'Importo',exact:true}).inputValue(),'');
  await page.keyboard.press('Escape'); assert.equal(await page.getByRole('dialog').count(),0,'+1 starts a clean draft');
  await start('editor&generic&singleSave&applePay');
  const dialog=page.getByRole('dialog');
  const order=await dialog.evaluate(el=>{
    const texts=[...el.querySelectorAll('p,input,button')];
    const idx=fn=>texts.findIndex(fn);
    return {source:idx(e=>e.textContent?.startsWith('Ricevuto da')),refund:idx(e=>e.textContent?.includes('Registra storno di una spesa')),amount:idx(e=>e.getAttribute('aria-label')==='Importo'),description:idx(e=>e.getAttribute('aria-label')==='Descrizione facoltativa'),categories:idx(e=>e.textContent?.includes('Casa'))};
  });
  assert.ok(order.source<order.refund && order.refund<order.amount && order.amount<order.description && order.description<order.categories,JSON.stringify(order));
  assert.equal(await dialog.getByRole('button',{name:'+1',exact:true}).count(),0);
  assert.notEqual(await page.evaluate(()=>document.activeElement?.tagName),'INPUT');
  await page.screenshot({path:fileURLToPath(new URL('./artifacts/editor-touch-tablet.png',import.meta.url))});
  await start(); await route('/settings');
  await page.getByRole('textbox',{name:'Cerca nelle impostazioni'}).fill('investimenti');
  const entry=page.getByRole('button',{name:/Investimenti.*Portafoglio/}); await entry.click();
  await page.getByRole('heading',{name:'Investimenti',exact:true}).waitFor();
  await page.locator('.ui-settings-detail').getByRole('button',{name:'Indietro',exact:true}).click();
  assert.equal(await page.getByRole('textbox',{name:'Cerca nelle impostazioni'}).inputValue(),'investimenti');
  await page.setViewportSize({width:1440,height:900});
  await entry.click(); await page.getByRole('heading',{name:'Investimenti',exact:true}).waitFor();
  await page.screenshot({path:fileURLToPath(new URL('./artifacts/settings-desktop-detail.png',import.meta.url))});
  const switchAlignment=await page.locator('.ui-settings-detail [aria-label="Gestione investimenti"]').evaluate(el=>{
    const target=el.getBoundingClientRect(),thumb=el.querySelector('span').getBoundingClientRect();
    return {height:target.height,offset:Math.abs(target.y+target.height/2-thumb.y-thumb.height/2)};
  });
  assert.ok(switchAlignment.height>=44 && switchAlignment.offset<1,JSON.stringify(switchAlignment));
  assert.equal(await page.locator('.ui-settings-menu').isVisible(),true,'desktop settings preserves the master');
  await route('/category-spending');
  await page.getByRole('button',{name:'6M',exact:true}).click();
  await route('/wealth'); await route('/category-spending');
  assert.ok((await page.getByRole('button',{name:'6M',exact:true}).getAttribute('class')).includes('text-gold'),'parent filter restored');
  await start('noAi');
  await page.getByRole('button',{name:'Altro',exact:true}).last().click();
  assert.equal(await page.locator('#ui3-quick-menu').getByRole('button',{name:'AI Coach'}).count(),0);
  await page.keyboard.press('Escape'); assert.equal(await page.locator('#ui3-quick-menu').count(),0);
  await start();
  const fingerprint=()=>page.locator('main').evaluate(el=>({numbers:[...el.querySelectorAll('.balance-num')].map(n=>n.textContent),paths:[...el.querySelectorAll('svg path')].map(n=>[n.getAttribute('d'),n.getAttribute('fill'),n.getAttribute('stroke')])}));
  const ui3=await fingerprint(); await start('ui=2'); const ui2=await fingerprint();
  assert.equal(await page.locator('html').getAttribute('data-ui-version'),'2.0');
  assert.deepEqual(ui3,ui2,'same fixture: original financial labels and SVG geometry');
  await start('editor&notices');
  assert.equal(await page.getByRole('dialog').count(),1);
  assert.equal(await page.getByRole('dialog',{name:'Avviso di prova'}).count(),0,'editor defers release and push notices');
  await page.keyboard.press('Escape');
  await page.getByRole('dialog',{name:'Avviso di prova'}).waitFor();
  assert.equal(await page.getByRole('dialog').count(),1);
  await page.getByRole('button',{name:'Ho capito',exact:true}).click();
  await page.getByRole('dialog',{name:'Notifiche',exact:true}).waitFor();
  assert.equal(await page.getByRole('dialog').count(),1,'deferred notice is not consumed');
  await page.getByRole('button',{name:'Non ora',exact:true}).click();
  assert.equal(await page.locator('[inert]').count(),0);
  await start(); await page.clock.install(); await route(`/wrapped/${new Date().getFullYear()}`);
  const wrapped=page.locator('.wrapped-shell'); await wrapped.waitFor();
  assert.deepEqual(await wrapped.evaluate(el=>[getComputedStyle(el).getPropertyValue('--c-bg').trim(),getComputedStyle(el).color]),['9 9 9','rgb(242, 236, 216)'],'Wrapped remains original dark shell, including its cover gradient');
  assert.ok(await wrapped.locator('.max-w-\\[430px\\]').evaluate(el=>el.getBoundingClientRect().width)<=430);
  const counter=wrapped.locator('p.text-center').last(); const first=await counter.textContent();
  await page.clock.runFor(5000); assert.equal(await counter.textContent(),first);
  await wrapped.locator('.max-w-\\[430px\\]').dispatchEvent('pointerdown',{clientX:500,clientY:400});
  await page.clock.runFor(30000); assert.equal(await counter.textContent(),first,'holding pauses the original timer');
  await wrapped.locator('.max-w-\\[430px\\]').dispatchEvent('pointercancel');
  await page.clock.runFor(500); assert.equal(await counter.textContent(),first);
  await page.clock.runFor(10000); assert.notEqual(await counter.textContent(),first,'resume uses residual time, not a new 15s');
  for(let n=0;n<25 && await page.locator('.wrapped-bar-fill').count();n++) {
    await wrapped.locator('.max-w-\\[430px\\]').dispatchEvent('pointerdown',{clientX:700,clientY:400});
    await wrapped.locator('.max-w-\\[430px\\]').dispatchEvent('pointerup',{clientX:600,clientY:400});
  }
  assert.equal(await page.locator('.wrapped-bar-fill').count(),0,'swipe finishes original stories');
  const wrappedCard=()=>wrapped.locator('.glass-card').first().evaluate(el=>{const s=getComputedStyle(el);return [s.backgroundColor,s.borderRadius,s.boxShadow];});
  const v3Card=await wrappedCard();
  await wrapped.getByRole('button',{name:/Imposta l'obiettivo/}).click();
  await wrapped.getByRole('button',{name:'Imposta obiettivo',exact:true}).click();
  await wrapped.getByText('Obiettivo impostato ✦').waitFor();
  await start('ui=2'); await route(`/wrapped/${new Date().getFullYear()}`);
  await wrapped.waitFor();
  await page.locator('.wrapped-bar-fill').first().waitFor();
  for(let n=0;n<25 && await page.locator('.wrapped-bar-fill').count();n++) {
    await wrapped.locator('.max-w-\\[430px\\]').dispatchEvent('pointerdown',{clientX:700,clientY:400});
    await wrapped.locator('.max-w-\\[430px\\]').dispatchEvent('pointerup',{clientX:600,clientY:400});
  }
  assert.deepEqual(v3Card,await wrappedCard(),'Wrapped summary materials stay identical in UI2/UI3');
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('PASS interactions: touch iPad, +1, source/refund/amount/categories order, settings return, filters, AI gate, UI2 parity, Wrapped residual timer/swipe');
} finally {await browser.close();}
