import { Transaction } from './types';

// Investments funded from the current account so that net worth stays
// consistent (cash converted to assets, not double-counted).
export const demoTransactions: Transaction[] = [
  // ── Maggio 2026 ──────────────────────────────────────────────────────────
  { id: 'd1',  date: '2026-05-01', description: 'Stipendio maggio',   amount: 2400,  type: 'income',     category: 'stipendio',  account: 'conto_corrente' },
  { id: 'd2',  date: '2026-05-02', description: 'Affitto',            amount: 750,   type: 'expense',    category: 'casa',       account: 'conto_corrente' },
  { id: 'd3',  date: '2026-05-03', description: 'Esselunga',          amount: 87.50, type: 'expense',    category: 'spesa',      account: 'conto_corrente' },
  { id: 'd4',  date: '2026-05-04', description: 'ETF S&P 500',        amount: 400,   type: 'investment', category: 'azioni_etf', account: 'conto_corrente' },
  { id: 'd5',  date: '2026-05-05', description: 'Trattoria da Mario', amount: 32,    type: 'expense',    category: 'ristoranti', account: 'contanti' },
  { id: 'd6',  date: '2026-05-07', description: 'Netflix',            amount: 12.99, type: 'expense',    category: 'abbonamenti',account: 'carta_credito' },
  { id: 'd7',  date: '2026-05-07', description: 'Spotify',            amount: 10.99, type: 'expense',    category: 'abbonamenti',account: 'carta_credito' },
  { id: 'd8',  date: '2026-05-08', description: 'Zara',               amount: 65,    type: 'expense',    category: 'shopping',   account: 'carta_credito' },
  { id: 'd9',  date: '2026-05-10', description: 'A conto risparmio',  amount: 300,   type: 'transfer',   category: 'trasferimento', account: 'conto_corrente', toAccount: 'conto_risparmio' },
  { id: 'd10', date: '2026-05-11', description: 'Conad',              amount: 45.20, type: 'expense',    category: 'spesa',      account: 'conto_corrente' },
  { id: 'd11', date: '2026-05-11', description: 'Bolletta luce',      amount: 89,    type: 'expense',    category: 'casa',       account: 'conto_corrente' },
  { id: 'd12', date: '2026-05-13', description: 'Bitcoin',            amount: 150,   type: 'investment', category: 'crypto',     account: 'conto_corrente' },
  { id: 'd13', date: '2026-05-14', description: 'Aperitivo centro',   amount: 24,    type: 'expense',    category: 'ristoranti', account: 'contanti' },
  { id: 'd14', date: '2026-05-14', description: 'Carburante',         amount: 55,    type: 'expense',    category: 'trasporti',  account: 'conto_corrente' },
  { id: 'd15', date: '2026-05-15', description: 'Coop',               amount: 62.80, type: 'expense',    category: 'spesa',      account: 'conto_corrente' },
  { id: 'd16', date: '2026-05-16', description: 'Progetto freelance', amount: 600,   type: 'income',     category: 'freelance',  account: 'conto_corrente' },
  { id: 'd17', date: '2026-05-17', description: 'H&M',                amount: 48,    type: 'expense',    category: 'shopping',   account: 'carta_credito' },
  { id: 'd18', date: '2026-05-18', description: 'Sushi bar',          amount: 41,    type: 'expense',    category: 'ristoranti', account: 'conto_corrente' },
  { id: 'd19', date: '2026-05-18', description: 'iCloud+',            amount: 2.99,  type: 'expense',    category: 'abbonamenti',account: 'carta_credito' },
  { id: 'd20', date: '2026-05-19', description: 'Esselunga',          amount: 93.40, type: 'expense',    category: 'spesa',      account: 'conto_corrente' },
  { id: 'd21', date: '2026-05-20', description: 'Farmacia',           amount: 22.50, type: 'expense',    category: 'salute',     account: 'contanti' },
  { id: 'd22', date: '2026-05-21', description: 'Cena con amici',     amount: 58,    type: 'expense',    category: 'ristoranti', account: 'conto_corrente' },
  { id: 'd23', date: '2026-05-22', description: 'Amazon',             amount: 34.99, type: 'expense',    category: 'shopping',   account: 'carta_credito' },
  { id: 'd24', date: '2026-05-23', description: 'Parcheggio',         amount: 12,    type: 'expense',    category: 'trasporti',  account: 'contanti' },
  // ── Aprile 2026 ──────────────────────────────────────────────────────────
  { id: 'd25', date: '2026-04-01', description: 'Stipendio aprile',   amount: 2400,  type: 'income',     category: 'stipendio',  account: 'conto_corrente' },
  { id: 'd26', date: '2026-04-03', description: 'Affitto',            amount: 750,   type: 'expense',    category: 'casa',       account: 'conto_corrente' },
  { id: 'd27', date: '2026-04-04', description: 'ETF MSCI World',     amount: 400,   type: 'investment', category: 'azioni_etf', account: 'conto_corrente' },
  { id: 'd28', date: '2026-04-07', description: 'Spesa settimana',    amount: 78,    type: 'expense',    category: 'spesa',      account: 'conto_corrente' },
  { id: 'd29', date: '2026-04-08', description: 'Netflix',            amount: 12.99, type: 'expense',    category: 'abbonamenti',account: 'carta_credito' },
  { id: 'd30', date: '2026-04-10', description: 'Ristorante',         amount: 38,    type: 'expense',    category: 'ristoranti', account: 'contanti' },
  { id: 'd31', date: '2026-04-12', description: 'A conto risparmio',  amount: 300,   type: 'transfer',   category: 'trasferimento', account: 'conto_corrente', toAccount: 'conto_risparmio' },
  { id: 'd32', date: '2026-04-15', description: 'Conad',              amount: 56.30, type: 'expense',    category: 'spesa',      account: 'conto_corrente' },
  { id: 'd33', date: '2026-04-18', description: 'Nike',               amount: 120,   type: 'expense',    category: 'shopping',   account: 'carta_credito' },
  { id: 'd34', date: '2026-04-20', description: 'Bolletta gas',       amount: 64,    type: 'expense',    category: 'casa',       account: 'conto_corrente' },
  { id: 'd35', date: '2026-04-28', description: 'Rimborso spese',     amount: 180,   type: 'income',     category: 'rimborso',   account: 'conto_corrente' },
  // ── Marzo 2026 ───────────────────────────────────────────────────────────
  { id: 'd36', date: '2026-03-01', description: 'Stipendio marzo',    amount: 2400,  type: 'income',     category: 'stipendio',  account: 'conto_corrente' },
  { id: 'd37', date: '2026-03-03', description: 'Affitto',            amount: 750,   type: 'expense',    category: 'casa',       account: 'conto_corrente' },
  { id: 'd38', date: '2026-03-05', description: 'ETF S&P 500',        amount: 400,   type: 'investment', category: 'azioni_etf', account: 'conto_corrente' },
  { id: 'd39', date: '2026-03-10', description: 'Spesa mensile',      amount: 280,   type: 'expense',    category: 'spesa',      account: 'conto_corrente' },
  { id: 'd40', date: '2026-03-15', description: 'Ristoranti vari',    amount: 145,   type: 'expense',    category: 'ristoranti', account: 'conto_corrente' },
  { id: 'd41', date: '2026-03-20', description: 'Shopping',           amount: 90,    type: 'expense',    category: 'shopping',   account: 'carta_credito' },
];
